const path = require('path');
const AdmZip = require('adm-zip');
const { XMLParser } = require('fast-xml-parser');
const officeParser = require('officeparser');
const ArtistModel = require('../models/artist.model');
const MusicService = require('./music.service');
const AppError = require('../utils/app-error');
const MAX_SONGS = 2000;
const clean = value => String(value || '').replace(/\r\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
const valueOf = (item, names) => names.map(name => item?.[name]).find(value => typeof value === 'string' || typeof value === 'number');
function makeSong(raw) { const title = clean(valueOf(raw, ['title','name','nome','titulo','songTitle'])), lyrics = clean(valueOf(raw, ['lyrics','lyric','letra','text','content','texto'])); return title && lyrics ? { title, lyrics, artist: clean(valueOf(raw, ['artist','artistName','artista','author','autor','composer'])), key: clean(valueOf(raw, ['key','tonality','tone','tom'])), bpm: Number(valueOf(raw, ['bpm'])) || null, source:'Holyrics' } : null; }
function collectSongs(value, results) { if (!value || results.length >= MAX_SONGS) return; if (Array.isArray(value)) return value.forEach(item => collectSongs(item, results)); if (typeof value !== 'object') return; const song = makeSong(value); if (song) results.push(song); Object.values(value).forEach(item => { if (typeof item === 'object') collectSongs(item, results); }); }
async function parsePresentation(file) { if (path.extname(file.originalname).toLowerCase()==='.ppt') throw new AppError('Arquivos .ppt antigos precisam ser salvos como .pptx no PowerPoint antes da importação.',422); const document = await officeParser.parseOffice(file.buffer,{ignoreNotes:true}); const lyrics=clean(await document.toText({newlineDelimiter:'\n'})); if(!lyrics) throw new AppError('Não foi possível localizar texto na apresentação.',422); return [{title:path.basename(file.originalname,path.extname(file.originalname)),lyrics,artist:'',key:'',bpm:null,source:'PowerPoint'}]; }
function parseHolyricsBackup(file) { let zip; try { zip=new AdmZip(file.buffer); } catch { throw new AppError('O arquivo .hbac não é um backup válido do Holyrics.',422); } const songs=[], parser=new XMLParser({ignoreAttributes:false,trimValues:true}); zip.getEntries().filter(e=>!e.isDirectory&&/\.(json|xml)$/i.test(e.entryName)).forEach(entry=>{const raw=entry.getData().toString('utf8').replace(/^\uFEFF/,'');try{collectSongs(/\.json$/i.test(entry.entryName)?JSON.parse(raw):parser.parse(raw),songs)}catch{/* Arquivo interno não relacionado. */}}); const unique=[...new Map(songs.map(song=>[`${song.title}\u0000${song.lyrics}`,song])).values()]; if(!unique.length) throw new AppError('Não foi possível identificar músicas neste backup .hbac. Exporte o backup completo pelo Holyrics e tente novamente.',422); return unique; }
async function preview(file) { if(!file) throw new AppError('Selecione um arquivo para importar.',400); const extension=path.extname(file.originalname).toLowerCase(); const songs=extension==='.hbac'?parseHolyricsBackup(file):(extension==='.ppt'||extension==='.pptx'?await parsePresentation(file):null); if(!songs) throw new AppError('Formato inválido. Envie um arquivo .hbac, .ppt ou .pptx.',400); const existing=new Set((await MusicService.listMusic()).map(item=>item.title.trim().toLocaleLowerCase('pt-BR'))); return songs.map((song,id)=>({id,...song,alreadyImported:existing.has(song.title.trim().toLocaleLowerCase('pt-BR'))})); }
async function importSongs(songs) { if(!Array.isArray(songs)||!songs.length) throw new AppError('Nenhuma música foi selecionada para importação.',400); const existing=await MusicService.listMusic(), byTitle=new Set(existing.map(x=>x.title.trim().toLocaleLowerCase('pt-BR'))), artists=await ArtistModel.findAll(), artistIds=new Map(artists.map(x=>[x.name.trim().toLocaleLowerCase('pt-BR'),x.id])); let imported=0,skipped=0; for(const item of songs.slice(0,MAX_SONGS)){const title=clean(item.title),lyrics=clean(item.lyrics), titleKey=title.toLocaleLowerCase('pt-BR');if(!title||!lyrics||byTitle.has(titleKey)){skipped++;continue}let artistId=null,artistName=clean(item.artist);if(artistName){const key=artistName.toLocaleLowerCase('pt-BR');artistId=artistIds.get(key);if(!artistId){artistId=(await ArtistModel.create({name:artistName})).id;artistIds.set(key,artistId)}}await MusicService.createMusic({title,artistId,type:'LOUVOR',energy:3,key:clean(item.key),bpm:Number(item.bpm)||null,duration:null,lyrics,youtubeUrl:null,cifraUrl:null,notes:`Importado de ${item.source||'arquivo'}.`,active:true,tagIds:[]});byTitle.add(titleKey);imported++} return {imported,skipped}; }
module.exports={preview,importSongs};
