const db = require('../models/db.model');
const AppError = require('../utils/app-error');
const { getCurrentChurchId } = require('../constants/church-context');
const W = require('../config/weights');
const okId = (id) => { const n = Number(id); if (!Number.isInteger(n) || n < 1) throw new AppError('Identificador inválido.', 400); return n; };
const body = (x = {}) => x;
const churchId = () => getCurrentChurchId();
async function tagsList() { return db.all('SELECT * FROM tags ORDER BY name'); }
async function tagGet(id) { const x = await db.get('SELECT * FROM tags WHERE id=?',[okId(id)]); if(!x) throw new AppError('Tag não encontrada.',404); return x; }
async function tagSave(data,id) { const x=body(data), name=String(x.name||'').trim(); if(!name) throw new AppError('Nome é obrigatório.',400); if(id){await tagGet(id); await db.run('UPDATE tags SET name=?,color=? WHERE id=?',[name,x.color||'#6F42C1',okId(id)]); return tagGet(id);} const r=await db.run('INSERT INTO tags(name,color) VALUES(?,?)',[name,x.color||'#6F42C1']); return tagGet(r.id); }
async function tagDelete(id){await tagGet(id); try{await db.run('DELETE FROM tags WHERE id=?',[okId(id)]);}catch(e){throw new AppError('Tag vinculada a músicas não pode ser removida.',409);}}
async function serviceTypes(){return db.all('SELECT id,name FROM service_types ORDER BY id');}
async function serviceList(){return db.all('SELECT s.*,st.name service_type_name, se.theme,se.preacher FROM services s JOIN service_types st ON st.id=s.service_type_id LEFT JOIN sermons se ON se.service_id=s.id WHERE s.church_id=? ORDER BY s.service_date DESC',[churchId()]);}
async function serviceGet(id){const x=await db.get('SELECT s.*,st.name service_type_name FROM services s JOIN service_types st ON st.id=s.service_type_id WHERE s.id=? AND s.church_id=?',[okId(id),churchId()]);if(!x)throw new AppError('Culto não encontrado.',404);x.sermon=await db.get('SELECT * FROM sermons WHERE service_id=?',[x.id]);return x;}
async function serviceSave(data,id){const x=body(data), type=okId(x.service_type_id);if(!x.service_date)throw new AppError('Data do culto é obrigatória.',400);let sid=id?okId(id):null;if(sid){await serviceGet(sid);await db.run('UPDATE services SET service_type_id=?,service_date=?,status=?,notes=? WHERE id=? AND church_id=?',[type,x.service_date,x.status||'PLANNED',x.notes||null,sid,churchId()]);}else{sid=(await db.run('INSERT INTO services(church_id,service_type_id,service_date,status,notes) VALUES(?,?,?,?,?)',[churchId(),type,x.service_date,x.status||'PLANNED',x.notes||null])).id;} if(x.sermon){const s=x.sermon;await db.run('INSERT INTO sermons(service_id,title,theme,book,chapter,verse_start,verse_end,preacher) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(service_id) DO UPDATE SET title=excluded.title,theme=excluded.theme,book=excluded.book,chapter=excluded.chapter,verse_start=excluded.verse_start,verse_end=excluded.verse_end,preacher=excluded.preacher',[sid,s.title||null,s.theme||null,s.book||null,s.chapter||null,s.verse_start||null,s.verse_end||null,s.preacher||null]);}return serviceGet(sid);}
async function serviceDelete(id){await serviceGet(id);await db.run('DELETE FROM services WHERE id=? AND church_id=?',[okId(id),churchId()]);}
async function preferences(){let x=await db.get('SELECT * FROM church_preferences WHERE church_id=?',[churchId()]);if(!x){await db.run('INSERT INTO church_preferences(church_id) VALUES(?)',[churchId()]);x=await db.get('SELECT * FROM church_preferences WHERE church_id=?',[churchId()]);}return {...x,quantidade_agitadas:x.quantidade_louvores>1?2:0,quantidade_calmas:x.quantidade_louvores>2?2:1};}
async function savePreferences(x){for(const k of ['dias_sem_repetir','quantidade_hinos','quantidade_agitadas','quantidade_calmas'])if(x[k]!==undefined&&(!Number.isInteger(Number(x[k]))||Number(x[k])<0||Number(x[k])>(k==='dias_sem_repetir'?365:20)))throw new AppError('Configuração inválida.',400);const p=await preferences();const h=x.quantidade_hinos??p.quantidade_hinos,u=x.quantidade_agitadas??2,c=x.quantidade_calmas??2;await db.run('UPDATE church_preferences SET dias_sem_repetir=?,quantidade_hinos=?,quantidade_louvores=? WHERE church_id=?',[x.dias_sem_repetir??p.dias_sem_repetir,h,Number(u)+Number(c),churchId()]);return {...await preferences(),quantidade_agitadas:Number(u),quantidade_calmas:Number(c)};}
async function candidates(){return db.all(`SELECT m.*,a.name artist_name, GROUP_CONCAT(t.name,'|') tags, MAX(h.performed_at) last_performed FROM music m LEFT JOIN artists a ON a.id=m.artist_id LEFT JOIN music_tags mt ON mt.music_id=m.id LEFT JOIN tags t ON t.id=mt.tag_id LEFT JOIN music_history h ON h.music_id=m.id AND h.church_id=? WHERE m.church_id=? AND m.active=1 GROUP BY m.id`,[churchId(),churchId()]);}
async function generate(x){const p=await preferences(), repeatDays=Number(x.repeat_days??p.dias_sem_repetir), counts={hymns:Number(x.hymns??p.quantidade_hinos),upbeat:Number(x.upbeat??2),calm:Number(x.calm??2)};if(Object.values(counts).reduce((a,b)=>a+b,0)<1)throw new AppError('Solicite ao menos uma posição.',400);const now=new Date(x.service_date||Date.now()), theme=String(x.theme||'').toLowerCase(), communion=!!x.communion, used=new Set(), warnings=[], items=[];const slots=[...Array(counts.hymns).fill('HINO'),...Array(counts.upbeat).fill('AGITADA'),...Array(counts.calm).fill('CALMA')];const all=await candidates();for(let i=0;i<slots.length;i++){const role=slots[i];let pool=all.filter(m=>!used.has(m.id)&&(role==='HINO'?m.type==='HINO':role==='AGITADA'?m.type==='LOUVOR'&&m.energy>=4:m.type==='LOUVOR'&&m.energy<=2));const blocked=pool.filter(m=>m.last_performed&&(now-new Date(m.last_performed))/86400000<repeatDays);pool=pool.filter(m=>!blocked.includes(m));let exceptional=false;if(!pool.length&&x.allow_repeat){pool=blocked;exceptional=true;}if(!pool.length){warnings.push(`Posição ${i+1} (${role}) não pôde ser preenchida.`);continue;}pool=pool.map(m=>{let score=100;const reasons=[];if(m.last_performed){const d=(now-new Date(m.last_performed))/86400000;score+=Math.min(d,365)/365*W.TIME_SINCE_LAST_PERFORMANCE;reasons.push({rule:'RECENCY',points:Math.round(score-100),message:'Tempo desde a última execução.'});}if(theme&&String(m.tags||'').toLowerCase().includes(theme)){score+=W.CONTEXT_MATCH;reasons.push({rule:'THEME',points:W.CONTEXT_MATCH,message:'Tag relacionada ao tema.'});}if(communion&&/(graça|comunhão|cruz|perdão|salvação|sacrifício|redenção|sangue)/i.test(m.tags||'')){score+=W.CONTEXT_MATCH;reasons.push({rule:'SERVICE_TYPE',points:W.CONTEXT_MATCH,message:'Adequada à Santa Ceia.'});}if(exceptional){score-=W.RECENT_REPEAT_PENALTY;reasons.push({rule:'RECENCY',points:-W.RECENT_REPEAT_PENALTY,message:'Repetição excepcional.'});}return {...m,score,reasons,exceptional};}).sort((a,b)=>b.score-a.score);const m=pool[0];used.add(m.id);items.push({position:i+1,role,music:m,score:Math.round(m.score),reasons:m.reasons,warnings:m.exceptional?['Repetição excepcional dentro da janela.']:[]});}return {qualityScore:Math.round(items.length/slots.length*100),warnings,criteria:{repeatDays,hymns:counts.hymns,upbeat:counts.upbeat,calm:counts.calm},items};}
async function repertoireGet(id){const r=await db.get('SELECT r.*,s.service_date FROM repertoires r JOIN services s ON s.id=r.service_id WHERE r.id=? AND r.church_id=?',[okId(id),churchId()]);if(!r)throw new AppError('Repertório não encontrado.',404);r.items=await db.all('SELECT ri.*,m.title,m.type,a.name artist_name FROM repertoire_items ri JOIN music m ON m.id=ri.music_id LEFT JOIN artists a ON a.id=m.artist_id WHERE ri.repertoire_id=? ORDER BY ri.position',[r.id]);return r;}
async function repertoireList(){const a=await db.all('SELECT id FROM repertoires WHERE church_id=? ORDER BY created_at DESC',[churchId()]);return Promise.all(a.map(x=>repertoireGet(x.id)));}
async function repertoireSave(x,id){const items=x.items||[], seen=new Set(),pos=new Set();if(!x.service_id)throw new AppError('Culto é obrigatório.',400);for(const i of items){if(!i.music_id||seen.has(i.music_id)||pos.has(i.position))throw new AppError('Músicas ou posições duplicadas.',409);seen.add(i.music_id);pos.add(i.position);if(!await db.get('SELECT id FROM music WHERE id=? AND church_id=? AND active=1',[i.music_id,churchId()]))throw new AppError('Música inativa ou inválida.',400);}let rid=id?okId(id):null;await db.transaction(async()=>{if(rid){const old=await repertoireGet(rid);if(old.status!=='DRAFT')throw new AppError('Somente rascunhos podem ser alterados.',409);await db.run('UPDATE repertoires SET service_id=?,quality_score=?,generation_context_json=? WHERE id=?',[x.service_id,x.quality_score||0,JSON.stringify(x.generation_context||{}),rid]);await db.run('DELETE FROM repertoire_items WHERE repertoire_id=?',[rid]);}else rid=(await db.run('INSERT INTO repertoires(church_id,service_id,status,quality_score,generation_context_json) VALUES(?,?,?,?,?)',[churchId(),x.service_id,'DRAFT',x.quality_score||0,JSON.stringify(x.generation_context||{})])).id;for(const i of items)await db.run('INSERT INTO repertoire_items(repertoire_id,music_id,position,role,score,reasons_json,warnings_json) VALUES(?,?,?,?,?,?,?)',[rid,i.music_id,i.position,i.role||'LOUVOR',i.score||0,JSON.stringify(i.reasons||[]),JSON.stringify(i.warnings||[])]);});return repertoireGet(rid);}
async function repertoireDelete(id){const r=await repertoireGet(id);await db.run('DELETE FROM repertoires WHERE id=?',[r.id]);}
async function repertoireStatus(id,status){const r=await repertoireGet(id);if(r.status===status)throw new AppError('Operação já realizada.',409);await db.transaction(async()=>{await db.run('UPDATE repertoires SET status=? WHERE id=?',[status,r.id]);if(status==='EXECUTED'){for(const i of r.items)await db.run('INSERT OR IGNORE INTO music_history(church_id,service_id,music_id,performed_at) VALUES(?,?,?,?)',[churchId(),r.service_id,i.music_id,r.service_date]);await db.run("UPDATE services SET status='COMPLETED' WHERE id=?",[r.service_id]);}});return repertoireGet(r.id);}
async function historyList(q={}){let where=' WHERE h.church_id=?',p=[churchId()];const map=[['startDate','h.performed_at>='],['endDate','h.performed_at<='],['musicId','h.music_id='],['artistId','m.artist_id='],['serviceTypeId','s.service_type_id='],['musicType','m.type='],['origin','h.origin=']];for(const [k,c] of map)if(q[k]){where+=' AND '+c+'?';p.push(q[k])}if(q.title){where+=' AND m.title LIKE ?';p.push('%'+q.title+'%')}const base=' FROM music_history h JOIN music m ON m.id=h.music_id LEFT JOIN artists a ON a.id=m.artist_id JOIN services s ON s.id=h.service_id JOIN service_types st ON st.id=s.service_type_id';const total=(await db.get('SELECT COUNT(*) total'+base+where,p)).total;const limit=Math.min(100,Math.max(1,Number(q.limit)||20)),page=Math.max(1,Number(q.page)||1),rows=await db.all('SELECT h.*,m.title,m.type,a.name artist_name,s.service_date,st.name service_type_name'+base+where+' ORDER BY h.performed_at DESC LIMIT ? OFFSET ?', [...p,limit,(page-1)*limit]);return {data:rows,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
async function historyGet(id){const x=await db.get('SELECT * FROM music_history WHERE id=? AND church_id=?',[okId(id),churchId()]);if(!x)throw new AppError('Histórico não encontrado.',404);return x;}
async function dashboard(){const totals=await db.get("SELECT SUM(active=1) music,SUM(active=1 AND type='HINO') hymns,SUM(active=1 AND type='LOUVOR') louvores,(SELECT COUNT(*) FROM artists WHERE church_id=?) artists,(SELECT COUNT(*) FROM repertoires WHERE church_id=?) repertoires,(SELECT COUNT(*) FROM services WHERE church_id=?) services FROM music WHERE church_id=?",[churchId(),churchId(),churchId(),churchId()]);const mostUsed=await db.all('SELECT m.title,COUNT(h.id) uses,MAX(h.performed_at) last_execution FROM music_history h JOIN music m ON m.id=h.music_id WHERE h.church_id=? GROUP BY m.id ORDER BY uses DESC LIMIT 10',[churchId()]);return {totals,mostUsed,recentRepertoires:await repertoireList()};}
async function historySave(x,id){const d=x||{}, musicId=okId(d.music_id),serviceId=d.service_id?okId(d.service_id):null;if(!d.performed_at)throw new AppError('Data de execução é obrigatória.',400);if(!await db.get('SELECT id FROM music WHERE id=? AND church_id=?',[musicId,churchId()]))throw new AppError('Música não encontrada.',404);if(serviceId&&!await db.get('SELECT id FROM services WHERE id=? AND church_id=?',[serviceId,churchId()]))throw new AppError('Culto não encontrado.',404);if(id){const old=await historyGet(id);if(old.origin==='AUTOMATIC')throw new AppError('Registro automático é protegido.',409);await db.run('UPDATE music_history SET music_id=?,service_id=?,performed_at=? WHERE id=?',[musicId,serviceId, d.performed_at,old.id]);return historyGet(old.id);}if(!serviceId)throw new AppError('Culto é obrigatório.',400);try{const r=await db.run("INSERT INTO music_history(church_id,service_id,music_id,performed_at,origin) VALUES(?,?,?,?, 'MANUAL')",[churchId(),serviceId,musicId,d.performed_at]);return historyGet(r.id);}catch(e){if(e.code==='SQLITE_CONSTRAINT')throw new AppError('Execução já registrada para esta música e culto.',409);throw e;}}
async function historyDelete(id){const h=await historyGet(id);if(h.origin==='AUTOMATIC')throw new AppError('Registro automático é protegido.',409);await db.run('DELETE FROM music_history WHERE id=?',[h.id]);}
module.exports={tagsList,tagGet,tagSave,tagDelete,serviceTypes,serviceList,serviceGet,serviceSave,preferences,savePreferences,repertoireGet,repertoireList,repertoireSave,repertoireDelete,repertoireStatus,historyList,historyGet,historySave,historyDelete,dashboard,generate:async x=>{const p=await preferences(),n=Number(x.hymns??p.quantidade_hinos)+Number(x.upbeat??2)+Number(x.calm??2),all=await candidates(),used=new Set(),items=[];for(let i=0;i<n;i++){const type=i<Number(x.hymns??p.quantidade_hinos)?'HINO':'LOUVOR',pool=all.filter(m=>m.type===type&&!used.has(m.id));if(pool.length){const m=pool[Math.floor(Math.random()*pool.length)];used.add(m.id);items.push({position:i+1,role:type,music:m,score:100,reasons:[],warnings:[]})}}return {qualityScore:Math.round(items.length/n*100),warnings:[],items}}};
async function generate(x){const p=await preferences(),days=Number(x.repeat_days??p.dias_sem_repetir),counts={hymns:Number(x.hymns??p.quantidade_hinos),upbeat:Number(x.upbeat??2),calm:Number(x.calm??2)},date=x.service_date||new Date().toISOString().slice(0,10),cutoff=new Date(`${date}T12:00:00`);cutoff.setDate(cutoff.getDate()-days);const slots=[...Array(counts.hymns).fill('HINO'),...Array(counts.upbeat).fill('AGITADA'),...Array(counts.calm).fill('CALMA')],all=await candidates(),used=new Set(),items=[],warnings=[];for(let i=0;i<slots.length;i++){const role=slots[i],pool=all.filter(m=>!used.has(m.id)&&(role==='HINO'?m.type==='HINO':role==='AGITADA'?m.type==='LOUVOR'&&m.energy>=4:m.type==='LOUVOR'&&m.energy<=2)&&(!m.last_performed||new Date(`${m.last_performed}T12:00:00`)<=cutoff));if(!pool.length){warnings.push(`Posição ${i+1} (${role}) não pôde ser preenchida sem repetir música dos últimos ${days} dias.`);continue}const seed=[...date].reduce((n,c)=>n+c.charCodeAt(0),i*17),m=pool[seed%pool.length];used.add(m.id);items.push({position:i+1,role,music:m,score:100,reasons:[{rule:'RECENCY',points:0,message:`Sem execução nos últimos ${days} dias.`}],warnings:[]})}return {qualityScore:Math.round(items.length/slots.length*100),warnings,criteria:{repeatDays:days,hymns:counts.hymns,upbeat:counts.upbeat,calm:counts.calm},items};}
