const DECISION_WEIGHTS = Object.freeze({
  CONTEXT_MATCH: 30,
  TIME_SINCE_LAST_PERFORMANCE: 25,
  ARTIST_DIVERSITY: 15,
  TAG_DIVERSITY: 15,
  ENERGY_FIT: 15,
  RECENT_REPEAT_PENALTY: 30
});

module.exports = DECISION_WEIGHTS;
